# Generated by Django 4.1.6 on 2023-03-10 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0002_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="issue",
        ),
        migrations.AddField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="webapp.project",
                verbose_name="Проект",
            ),
        ),
    ]
