# Generated by Django 4.1.6 on 2023-03-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_projectuser_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectuser',
            options={'verbose_name': 'Пользователь проекта', 'verbose_name_plural': 'Пользователи проекта'},
        ),
    ]
